# Generated by Django 2.0.5 on 2024-04-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProduct',
            fields=[
                ('pro_name', models.CharField(max_length=32)),
                ('pro_description', models.TextField()),
                ('pro_image', models.TextField(default='')),
                ('pro_code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('pro_range', models.CharField(max_length=32)),
                ('pro_features', models.TextField(default='')),
                ('pro_price', models.IntegerField()),
                ('pro_price_per_user', models.IntegerField()),
                ('pro_price_plumber', models.IntegerField()),
                ('pro_price_prime', models.IntegerField()),
            ],
        ),
    ]
